excluded:
- Pods

disabled_rules:
- cyclomatic_complexity
- file_length
- function_body_length
- line_length
- nesting
- type_body_length

opt_in_rules:
- anyobject_protocol
- array_init
- attributes
- closure_end_indentation
- closure_spacing
- contains_over_first_not_nil
- convenience_type
- discouraged_object_literal
- empty_xctest_method
- explicit_init
- extension_access_modifier
- fallthrough
- fatal_error_message
- file_name
- first_where
- force_unwrapping
- function_default_parameter_at_end
- implicit_return
- joined_default_parameter
- let_var_whitespace
- literal_expression_end_indentation
- modifier_order
- multiline_arguments
- multiline_function_chains
- multiline_parameters
- nimble_operator
- no_extension_access_modifier
- number_separator
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- prefixed_toplevel_constant
- private_action
- private_outlet
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- required_enum_case
- single_test_class
- sorted_first_last
- sorted_imports
- strict_fileprivate
- switch_case_on_newline
- trailing_closure
- unavailable_function
- unneeded_parentheses_in_closure_argument
- untyped_error_in_catch
- vertical_parameter_alignment_on_call
- yoda_condition

identifier_name:
  excluded:
  - id

trailing_comma:
  mandatory_comma: true
